// SPDX-License-Identifier: MIT
// Copyright (c) Sean Terry (seanterry@outlook.com) and Contributors
// This file is licensed to you under the MIT license.

namespace Identifiable;

/// <summary>
/// Layouts for time-based GUIDs.
/// </summary>
public enum TimeGuidLayout
{
    /// <summary>
    /// GUID layout as described in RFC 4122 Section 4.1.2.
    /// https://tools.ietf.org/html/rfc4122#section-4.1.2
    /// </summary>
    Standard = 1,

    /// <summary>
    /// Custom layout optimized for SQL Server clustered indexes.
    /// Identifiers in this layout:
    /// - Can be transposed to/from those in the <see cref="Standard"/> layout.
    /// - Will identify as Variant 0 due to transposition.
    /// - Will sort sequentially in SQL Server.
    /// - Will not collide with any RFC 4122 compliant GUIDs.
    /// - May collide with other variant 0 layouts.
    /// </summary>
    /// <remarks>
    /// Because these are not generated by the database itself, they will not be perfectly
    /// sequential due to race conditions.
    /// </remarks>
    SqlServer,

    /// <summary>
    /// Custom layout optimized for sorting sequentially in PostgreSQL.
    /// Identifiers in this layout:
    /// - Can be transposed to/from those in the <see cref="Standard"/> layout.
    /// - Will identify as Variant 0 due to transposition.
    /// - Will sort sequentially in SQL Server.
    /// - Will not collide with any RFC 4122 compliant GUIDs.
    /// - May collide with other variant 0 layouts.
    /// </summary>
    /// <remarks>
    /// Because these are not generated by the database itself, they will not be perfectly
    /// sequential due to race conditions.
    /// </remarks>
    PostgreSql
}
